### ISSUE TITLE
Is there any specific reason for creating your own BufferManager

### ISSUE THREAD

**Issue by abdullah2993** [EventStore/buffer-manager#2]
Is there any specific reason for creating your own BufferManager class instead of using System.ServiceModel.Channels.BufferManger? any performance reasons?

**Comment by gregoryyoung** [comment]
Never saw it before to be fair the code was written in 2005-2006

**Comment by gregoryyoung** [comment]
Some context for others that may come by this
https://www.google.com/url?sa=t&source=web&rct=j&ei=LpbXVN2OBpDeateBgYAJ&url=http://codebetter.com/gregyoung/2007/06/18/async-sockets-and-buffer-management/&ved=0CB4QFjAB&usg=AFQjCNEajAO_kDX6b-ehyPpTbgDmp_2dYA
